on:
  push:
    branches:
      - master

jobs:
  update-dev-infra:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [Developement]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        working-directory: ./terraform
        run: |
          docker build -t terragrunt:local --build-arg TF_VERSION=${tf_version} --build-arg TG_VERSION=${tg_version} .
  update-staging-infra:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [Staging]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        working-directory: ./terraform
        run: |
          docker build -t terragrunt:local --build-arg TF_VERSION=${tf_version} --build-arg TG_VERSION=${tg_version} .
  update-production-infra:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [Production]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        working-directory: ./terraform
        run: |
          docker build -t terragrunt:local --build-arg TF_VERSION=${tf_version} --build-arg TG_VERSION=${tg_version} .
